### ISSUE TITLE
PKCS10 example fails on Microsoft Edge (new default Windows browser)

### ISSUE THREAD

**Issue by mikemaccana** [PeculiarVentures/ASN1.js#12]
Windows 10 has a new default browser, Microsoft Edge, with webcrypto support (using the later promises version of the spec).

https://pkijs.org/examples/PKCS10_complex_example.html fails on Edge, version 20.10166.0.0:

```
var pkcs10encoded = pkcs10schema.toBER(false);
```

With: 

```
 Unable to get property 'toBER' of undefined or null reference.
```

On asn1.js line 1475.

**Comment by YuryStrozhevsky** [comment]
In fact the issue should be inside "PKI.js" project. As for Edge I did not check PKI.js/ASN1.js in this browser. Since it is in development at the moment I can not guarantee that Microsoft implemented Web Cryptography API correctly. So, I do not consider this issue as a bug because all PKI.js examples work in latest Chrome, where I 100% sure in correct implementation of WebCrypto. As a conclusion: use latest Chrome versions. And probably in a future I will be able to check PKI.js inside Edge.

**Comment by rmhrisk** [comment]
Keeping open until we can confirm release version of Edge works with PKIjs

**Comment by mikemaccana** [comment]
This was closed without any update, but (from testing it) it looks like PKIJS 2 works on Edge now - @YuryStrozhevsky is that correct?

**Comment by rmhrisk** [comment]
yes it does

**Comment by YuryStrozhevsky** [comment]
In fact there is no difference in browser support between V1 and V2. As soon as browser has no native ES6 module support all the PKIjs code would be transpiled using Babel. 

If you are interested in testing any browser support you could use [existing live examples](http://pkijs.org/#examples). Please notice there are all for V2 version. 

Also you could check "support level" for WebCrypto API in any browser: just open [this link](https://peculiarventures.github.io/pv-webcrypto-tests/).

**Comment by mikemaccana** [comment]
Yeah it looks like an implementation bug in early Edges (which did have webcrypto just a half baked implementation). Glad to see it's fixed.
