### ISSUE TITLE
Implicite tagging 

### ISSUE THREAD

**Issue by jeremy-saidani** [PeculiarVentures/ASN1.js#45]
Hi,

I would like to encode : 
```asn1
DeviceID ::= CHOICE {
        dialingNumber	[0] IMPLICIT	NumberDigits,
 	deviceNumber	[1] IMPLICIT	DeviceNumber
}

NumberDigits	::= IA5String
DeviceNumber	::= INTEGER
```
How can I handle implicite tag ?
I saw this issue https://github.com/PeculiarVentures/ASN1.js/issues/9 but I didin't really understand it.

I have to do a Sequence of DeviceID, so here is my code : 
``` javascript
var mySequence = new asn1.Sequence({
    value: [
        new asn1.Integer({value: 2000})
    ]
)}
```
I just need to add the implicite tag [1], but how ?

Thx

**Comment by YuryStrozhevsky** [comment]
@jeremy-saidani The ASN1js library is a complex library, intended to cover any possible case of ASN.1 representations or ASN.1 data. And thus in some cases there is no "simple way" - in order to handle these "complex case" you need to understand ASN.1 data representation.

In your case you need to create schema for `IMPLICIT` tagging. But in order to do this you firstly need to understand what is tagging in ASN.1. I do recommend you to read [**my article**](https://www.strozhevsky.com/free_docs/asn1_by_simple_words.pdf) about ASN.1. So, you need to understand that `IMPLICIT` tagging is for making a "shell" for underlying object. In case of primitive intial types the "shell" would be ASN.1 `Primitive` class, in case of complex initial type the "shell" will be `Constructed` ASN.1 data type. At the end the class having ASN.1 schema for your particular type using ASN1js will looks like this:
```javascript
class DeviceID {
	
	static schema(parameters = {})
	{
		const names = getParametersValue(parameters, "names", {});

		return (new asn1js.Choice({
			value: [
				new asn1js.Primitive({
					name: (names.deviceID || ""),
					idBlock: {
						tagClass: 3,
						tagNumber: 0
					}
				}), // Representation for "dialingNumber"
				new asn1js.Primitive({
					name: (names.deviceID || ""),
					idBlock: {
						tagClass: 3,
						tagNumber: 1
					}
				}), // Representation for "deviceNumber"
			]
		}));
	}

	fromSchema(schema)
	{
		//region Clear input data first
		clearProps(schema, [
			"deviceID"
		]);
		//endregion

		//region Check the schema is valid
		const asn1 = asn1js.compareSchema(schema,
			schema,
			DeviceID.schema({
				names: {
					deviceID: "deviceID"
				}
			})
		);

		if(asn1.verified === false)
			throw new Error("Object's schema was not verified against input data for DeviceID");
		//endregion

		switch(asn1.result.deviceID.idBlock.tagNumber)
		{
			case 0:
				this.deviceID = new asn1js.IA5String({ value: arrayBufferToString(asn1.result.deviceID.valueBlock.valueHex) });
				break;
			case 1:
				this.deviceID = new asn1js.Integer({ valueHex: asn1.result.deviceID.valueBlock.valueHex });
				break;
			default:
				throw new Error("Object's schema was not verified against input data for DeviceID");
		}
	}
	
	toSchema()
	{
		return new asn1js.Primitive({
			idBlock: {
				tagClass: 3,
				tagNumber: ((this.deviceID.constructor.blockName === asn1js.IA5String.blockName) ? 0 : 1)
			},
			valueHex: this.deviceID.valueBlock.valueHex
		});
	}
}
```
I did not check the class on real data, but I bet all would work just fine. In case of questions please let me know.

**Comment by jeremy-saidani** [comment]
Thx for your answer !

Could I do something like that :

``` javascript
function MonitorStartArgument(number){
    return new asn1js.Sequence({
        value: [
            new asn1js.Primitive({
                name: 'deviceNumber',
                idBlock: {
                    tagClass: 3,
                    tagNumber: 1
                },
                value: number
            })
        ],
    }).toBER(false);
}
```
Because I will never have to decode it. I just need to encode it.


But thanks for your exemple, I have an other object to decode and I think you helped me

**Comment by jeremy-saidani** [comment]
So for [APPLICATION] tag I have to use `Constructed `ASN.1 data type ?

My exemple : 

```
ConnectionID ::= [APPLICATION 11] IMPLICIT SEQUENCE
	{call	[2] IMPLICIT	OCTET STRING	OPTIONAL,
	device	CHOICE
		{staticID	DeviceID,
		dynamicID	[3] IMPLICIT	OCTET STRING}	OPTIONAL}
```

**Comment by YuryStrozhevsky** [comment]
@jeremy-saidani Using of `Constructed` or `Primitive` depends on underlying type, not from tag type. The `APPLICATION` tag type has number `2`, this is correct.
