### ISSUE TITLE
Schema encoding using DER encoding rules

### ISSUE THREAD

**Issue by jamesperi** [PeculiarVentures/ASN1.js#46]
It looks like i'm able to encode a CMS schema using something like

```javascript
const cms = new pkijs.ContentInfo({
  contentType: "1.2.840.113549.1.9.16.1.42",
  content: new asn1js.Utf8String({ value: xml })
})

return toBase64(arrayBufferToString(cms.toSchema().toBER(false)))

```
Though it doesn't look like there is a way to encode with DER rules as is required for 

[rfc8572](https://tools.ietf.org/html/rfc8572#section-3.1)

> The conveyed information artifact is a Cryptographic Message Syntax
> (CMS) structure, as described in [RFC5652], encoded using ASN.1
> distinguished encoding rules (DER), as specified in ITU-T X.690
> [ITU.X690.2015].  The CMS structure MUST contain content conforming
> to the YANG module specified in Section 6.3.

Is DER encoding a schema like this possible or outside the scope of this package ?

**Comment by YuryStrozhevsky** [comment]
@jamesperi First of all some ASN.1 theory. The BER set of encoding rules is a major set of rules for ASN.1. The DER set of rules is a subset of BER. The DER has some of restrictions for BER the major is not having constructed values for OCTETSTING class. So, in order to encode ASN.1 to be compliant with DER you just can use BER and do not encode OCTETSTING values in constructed form. It is all possible using ASN1js. 

As for CMS: in fact most of the parts of CMS message are encoded using DER. But there are some limitations where in CMS standard RFC5652 stated something like "need not be DER encoded". In this case it is up to developer which encoding rules to use - DER or BER. The PKIjs library is fully compliant with CMS standard.

**Comment by jamesperi** [comment]
Thanks so much!
